#!/usr/bin/env bash
set -e

CALLER_DIR="$(pwd)"
SCRIPT_PATH="$(readlink -f "$0" || realpath "$0")"
ROOT_DIR="$(dirname "$SCRIPT_PATH")"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"

if [ -z "$(docker compose -f "$COMPOSE_FILE" ps -q subenum-db)" ]; then
    docker compose -f "$COMPOSE_FILE" up -d subenum-db
fi

docker compose -f "$COMPOSE_FILE" build subenum

docker compose -f "$COMPOSE_FILE" run --rm \
    --entrypoint python3 \
    -v "$CALLER_DIR":/subenum \
    -w /subenum \
    subenum \
    /app/src/subenum.py "$@"
